### ISSUE TITLE
Widget Routing Issue using React HashRouter

### ISSUE THREAD

**Issue by kylefoley** [okta/okta-signin-widget#300]
Hello,

When redirecting people who are not authenticated to the login page, which is supposed to be localhost:3000/#/auth/login, the changes the url bar to localhost:3000/auth/login#/auth/login. If I remove the Okta Widget from the login page, the routing works perfect. Anyone else have any issues like this? I can provide code snippets as requested. Here is my auth checker redirect 

`let PrivateRoute = withAuth(({ component: Component, component, auth, ...rest }) => (`
  `<Route {...rest} children={props  => (`
    `auth.isAuthenticated() ? (`
      `renderMergedProps(component, props, rest)`
  `) : (`
    `<Redirect to="/auth/login"/>`
    `)`
  `)}/>`
`));`

Before you ask, if I make the Redirect = '#/auth/login', it still dosn't work. 

Thanks!

**Comment by rchild-okta** [comment]
@lboyette-okta or @samerfanek-okta, any ideas on this? I'm guessing it's because we start [backbone.history](http://backbonejs.org/#History-start) with our router (even though w/out the router feature flag it's not exposed), and it's assuming the root url is the current page. In this case, the `root` should be /auth/login.

If this is the case, there are a couple options:

1. Straightforward - expose a config option to set the root url, and pass it in to the router start call [here](https://github.com/okta/okta-signin-widget/blob/master/src/util/BaseLoginRouter.js#L278)
2. More work, but reduces our exposure to other frameworks with their own routing - if the router feature flag is not enabled, don't use Backbone.history. We currently override the navigate/etc events when this is the case - we'd need to have another override on the start call, or alternatively just switch out and maintain our own internal state and not depend on the router at all.

**Comment by rchild-okta** [comment]
@kylefoley if you wanted to try this on your own, you can modify [this line](https://github.com/okta/okta-signin-widget/blob/master/src/util/BaseLoginRouter.js#L278) to look like this:

```javascript
Okta.Router.prototype.start.call(this, { 
  pushState: pushState,
  root: '/auth/login' 
});
```

To try the change, you'd have to clone this repo and [follow these steps](https://github.com/okta/okta-signin-widget#developing-the-sign-in-widget).

**Comment by kylefoley** [comment]
Alright, I'll give that a shot and report back. Thanks!

**Comment by kylefoley** [comment]
This seemed to fix the issue, although I've been having the issue where the login box does not show up, so I changed my package.JSON's "main" to `"./dist/js/okta-sign-in-no-jquery.js"` for it to work. Now that i'm not using that path, it won't load the box. Any suggestions?

**Comment by kylefoley** [comment]
This issue is referenced in [https://github.com/okta/okta-signin-widget/issues/215](url)

**Comment by kylefoley** [comment]
@rchild-okta Any update on this? Wasn't able to get the widget to render using the method you suggested, but it seemed to sort the routing issue

**Comment by rchild-okta** [comment]
@kylefoley sorry, no updates from me - I haven't had a chance to look at this yet. @samerfanek-okta, is this something you can look into?

**Comment by lboyette-okta** [comment]
@kylefoley this is now fixed in master and will be released in 2.6.0

**Comment by MangeshTak** [comment]
Hello,
I am using okta signin widget, but implicit/callback is still not working with react-hashrouter.
Is there any way (other than browserRouter) I can make this work?

Thanks

**Comment by haishengwu-okta** [comment]
@MangeshTak does turn off `features.router` work for u?

**Comment by MangeshTak** [comment]
I have not set **features.router** in my application, but its default value is false as per doc ,
https://github.com/okta/okta-signin-widget

Is there any other way?

Thanks
